# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        go install src.techknowlogick.com/xgo@latest
        xgo --targets=linux/arm64 -out build/gundam-displays github.com/ElijahB09/Gundam-Displays
        mkdir -p ${{ github.workspace }}/build-artifacts
        cp -r ./build/* ${{ github.workspace }}/build-artifacts/

      env:
        ARTIFACTS_DIR: ${{ github.workspace }}/build-artifacts

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.RPI_HOSTNAME }}
        username: ${{ secrets.RPI_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: whoami

